import type { ScanFinding } from './types';
import type { Locale } from '@/lib/i18n/translations';
import {
  INFO_EMAIL_LEAKAGE,
  INFO_PHONE_LEAKAGE,
  INFO_SENSITIVE_COMMENTS,
  INFO_INTERNAL_IP,
  INFO_OPEN_REDIRECT,
  STACK_TRACE_EXPOSED,
  entryToFinding,
} from './knowledge-base';

export interface InfoLeakageResult {
  findings: ScanFinding[];
}

// ---- Patterns ----

// Email prefixes that are clearly non-sensitive (public contact addresses)
const EXCLUDED_EMAIL_PREFIXES = [
  'noreply', 'no-reply', 'noreply-',
  'admin', 'webmaster', 'postmaster',
  'info@', 'support@', 'help@',
  'abuse@', 'spam@',
  'mailer-daemon', 'root@',
  'privacy@', 'security@', 'legal@', 'press@', 'media@',
  'partnerships@', 'investors@', 'careers@', 'jobs@', 'hr@',
  'example@', 'test@', 'sample@', 'demo@', 'fake@',
  'user@', 'email@', 'name@', 'yourname@',
  'contact@', 'hello@', 'hi@', 'team@', 'sales@',
];

// Domains used for documentation examples — never real leaks
const EXCLUDED_EMAIL_DOMAINS = [
  'example.com', 'example.org', 'example.net',
  'test.com', 'test.org',
  'domain.com', 'yourdomain.com', 'yourcompany.com',
  'company.com', 'email.com',
  'acme.com',
  'foo.com', 'bar.com',
  'placeholder.com',
];

function isExcludedEmail(email: string): boolean {
  const lower = email.toLowerCase();
  if (EXCLUDED_EMAIL_PREFIXES.some((prefix) => lower.startsWith(prefix))) return true;
  const domain = lower.split('@')[1] || '';
  if (EXCLUDED_EMAIL_DOMAINS.includes(domain)) return true;
  return false;
}

// Email pattern: match common email formats
const EMAIL_PATTERN = /[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}/g;

// Phone patterns (international formats)
const PHONE_PATTERNS = [
  // International format with + prefix: +1 234 567 8900, +44 20 7946 0958
  // Must start with + or 00 — no decimal points allowed in match
  /\+\d{1,3}[\s\-]?\(?\d{2,4}\)?[\s\-]?\d{3,4}[\s\-]?\d{3,4}/g,
  // US-style with parentheses: (234) 567-8900 or (234) 567 8900
  /\(\d{3}\)\s*\d{3}[\s\-]\d{4}/g,
  // International 00-prefix: 001234567890
  /00\d{1,3}[\s\-]?\d{7,12}/g,
];

// Internal IP ranges
const INTERNAL_IP_PATTERNS = [
  /10\.\d{1,3}\.\d{1,3}\.\d{1,3}/g,
  /172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}/g,
  /192\.168\.\d{1,3}\.\d{1,3}/g,
  /169\.254\.\d{1,3}\.\d{1,3}/g,
  /127\.\d{1,3}\.\d{1,3}\.\d{1,3}/g,
];

// Internal hostname patterns
const INTERNAL_HOSTNAME_PATTERNS = [
  /\.local\b/g,
  /\.internal\b/g,
  /\.localhost\b/g,
  /\.lan\b/g,
  /\.intranet\b/g,
  /\.corp\b/g,
  // database-style hostnames
  /(?:db|database|mysql|postgres|redis|mongo|elastic)\d*\.(?:internal|local|corp|lan)\b/gi,
];

// Benign comment patterns — copyright/license/attribution text, never sensitive
const BENIGN_COMMENT_PATTERNS = [
  /copyright\s+(?:\(c\)|©|\d{4})/i,
  /©\s*\d{4}/,
  /all rights reserved/i,
  /licensed? under the\s+\w/i,
  /mit license/i,
  /apache license/i,
  /gnu (?:general )?public license/i,
  /permission is hereby granted/i,
  /redistribution and use in source/i,
  /this (?:file|software|library|code|program) is (?:part of|free|released|provided)/i,
  /^[\s\n]*@license\b/i,
  /^[\s\n]*@preserve\b/i,
  /^[\s\n]*@author\b/i,
  /generated by\b/i,
  /build\s*:\s*\d{4}/i,
];

// Sensitive comment patterns
const SENSITIVE_COMMENT_PATTERNS = [
  // Passwords and keys
  /password\s*[:=]\s*["'][^"']{3,}["']/i,
  /passwd\s*[:=]\s*["'][^"']{3,}["']/i,
  /api[_-]?key\s*[:=]\s*["'][^"']{5,}["']/i,
  /secret[_-]?key\s*[:=]\s*["'][^"']{5,}["']/i,
  /private[_-]?key\s*[:=]\s*["'][^"']{5,}["']/i,
  /access[_-]?token\s*[:=]\s*["'][^"']{5,}["']/i,
  /auth[_-]?token\s*[:=]\s*["'][^"']{5,}["']/i,
  /credentials?\s*[:=]\s*["'][^"']{5,}["']/i,
  /connection[_-]?string\s*[:=]\s*["'][^"']{5,}["']/i,
  // TODO with security notes
  /todo\s*[:\s].*?(?:security|vulnerability|exploit|fix|hack|inject|xss|csrf|sqli|auth)/i,
  /hack\s*[:\s].*?(?:fix|remove|this|temporary|workaround)/i,
  /debug\s*[:\s].*?(?:remove|delete|disable|temporary|fixme)/i,
  /fixme\s*[:\s].*?(?:security|vulnerability|exploit|inject|broken)/i,
  /xxx\s*[:\s].*?(?:remove|delete|temp|debug|hack)/i,
  // Debug info
  /debug\s*[:=]\s*(?:true|1|on)\b/i,
  /debug_mode\s*[:=]\s*(?:true|1|on)\b/i,
  /verbose\s*[:=]\s*(?:true|1)\b/i,
  /dev[_-]?mode\s*[:=]\s*(?:true|1|on)\b/i,
  /staging[_-]?mode\s*[:=]\s*(?:true|1|on)\b/i,
  // Internal paths or URLs
  /(?:internal|admin|backend|staging|dev)\.(?:url|host|endpoint|path|server)\s*[:=]\s*["'][^"']+["']/i,
  /(?:ssh|ftp|sftp):\/\/[^<\s"']+/i,
];

// API key patterns in meta tags and hidden inputs (different from js-analyzer)
const META_API_KEY_PATTERNS = [
  /<meta\s+[^>]*name\s*=\s*["'](?:api[_-]?key|google[_-]?maps[_-]?key|stripe[_-]?key|recaptcha[_-]?key|firebase[_-]?key|sendgrid[_-]?key)["'][^>]*content\s*=\s*["']([^"']+)["']/gi,
  /<meta\s+[^>]*content\s*=\s*["']([^"']+)["'][^>]*name\s*=\s*["'](?:api[_-]?key|google[_-]?maps[_-]?key|stripe[_-]?key|recaptcha[_-]?key|firebase[_-]?key|sendgrid[_-]?key)["']/gi,
];

// Narrow to clearly API-related names only — "token" and "key" alone are
// almost always CSRF tokens in hidden form fields, not leaked API credentials.
const HIDDEN_INPUT_PATTERNS = [
  /<input[^>]*type\s*=\s*["']hidden["'][^>]*name\s*=\s*["'](?:api[_-]?key|api[_-]?token|access[_-]?token|auth[_-]?token|secret[_-]?key|private[_-]?key|password|credential)["'][^>]*value\s*=\s*["']([^"']{8,})["']/gi,
  /<input[^>]*name\s*=\s*["'](?:api[_-]?key|api[_-]?token|access[_-]?token|auth[_-]?token|secret[_-]?key|private[_-]?key|password|credential)["'][^>]*type\s*=\s*["']hidden["'][^>]*value\s*=\s*["']([^"']{8,})["']/gi,
];

// Meta refresh open redirect
const META_REFRESH_PATTERN = /<meta\s+[^>]*http-equiv\s*=\s*["']refresh["'][^>]*content\s*=\s*["'](\d+);\s*url\s*=\s*([^"']+)["']/gi;

// ---- Detection functions ----

function detectEmailLeakage(html: string, locale: Locale): ScanFinding[] {
  const findings: ScanFinding[] = [];
  const emails: string[] = [];

  // Remove script, style, SVG, noscript content to avoid false positives
  const cleanHtml = html.replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<svg[\s\S]*?<\/svg>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<[^>]+>/g, ' ');

  let match: RegExpExecArray | null;
  const emailRegex = new RegExp(EMAIL_PATTERN.source, 'g');
  while ((match = emailRegex.exec(cleanHtml)) !== null) {
    const email = match[0];
    if (!isExcludedEmail(email) && !emails.includes(email)) {
      emails.push(email);
    }
  }

  if (emails.length > 0) {
    // Limit display to first 10 emails
    const displayEmails = emails.slice(0, 10).join(', ');
    const details = emails.length > 10
      ? `${displayEmails} ... and ${emails.length - 10} more`
      : displayEmails;

    findings.push(
      entryToFinding(INFO_EMAIL_LEAKAGE, { evidence: displayEmails, details }, locale),
    );
  }

  return findings;
}

function detectPhoneLeakage(html: string, locale: Locale): ScanFinding[] {
  const findings: ScanFinding[] = [];
  const phones: string[] = [];

  // Remove script, style, SVG, noscript, and template content
  // SVG paths contain coordinate data that looks like phone numbers
  const cleanHtml = html.replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<svg[\s\S]*?<\/svg>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<template[\s\S]*?<\/template>/gi, ' ');

  for (const pattern of PHONE_PATTERNS) {
    const regex = new RegExp(pattern.source, 'g');
    let match: RegExpExecArray | null;
    while ((match = regex.exec(cleanHtml)) !== null) {
      const phone = match[0].trim();
      const matchIndex = match.index;
      const digitsOnly = phone.replace(/\D/g, '');

      // Filter: must have exactly 10-15 digits
      if (digitsOnly.length < 10 || digitsOnly.length > 15) continue;

      // Filter: no IP addresses
      if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(phone)) continue;

      // Filter: no decimal points (phone numbers don't have them, coordinates do)
      if (/\d+\.\d+/.test(phone)) continue;

      // Filter: no adjacent letter-digit transitions (coordinate data like 94.992 107)
      if (/\d[a-zA-Z]|[a-zA-Z]\d/.test(phone.replace(/[\s\-()]/g, ''))) continue;

      // Filter: must have reasonable phone structure (grouping or separator)
      // Pure 10+ digit strings without any separators are likely not phone numbers
      if (!/[\s\-()]/.test(phone) && !/^\+/.test(phone)) continue;

      // Filter: exclude if contains sequences of 3+ identical digits (likely not a phone)
      if (/(\d)\1{3,}/.test(digitsOnly)) continue;

      // Filter: check surrounding context — if phone is part of a filename/identifier/hash,
      // it's not a real phone number (e.g., "accordion-2-730955545f07.webp")
      const before = cleanHtml.slice(Math.max(0, matchIndex - 5), matchIndex);
      const after = cleanHtml.slice(matchIndex + phone.length, matchIndex + phone.length + 5);
      const beforeChar = before.trim().slice(-1);
      const afterChar = after.trim()[0];
      // If preceded or followed by alphanumeric char, it's part of a larger token
      if (beforeChar && /[a-zA-Z0-9_]/.test(beforeChar)) continue;
      if (afterChar && /[a-zA-Z0-9_]/.test(afterChar)) continue;

      if (!phones.includes(phone)) {
        phones.push(phone);
      }
    }
  }

  if (phones.length > 0) {
    const displayPhones = phones.slice(0, 10).join(', ');
    const details = phones.length > 10
      ? `${displayPhones} ... and ${phones.length - 10} more`
      : displayPhones;

    findings.push(
      entryToFinding(INFO_PHONE_LEAKAGE, { evidence: displayPhones, details }, locale),
    );
  }

  return findings;
}

function detectSensitiveComments(html: string, locale: Locale): ScanFinding[] {
  const findings: ScanFinding[] = [];
  const matches: string[] = [];

  // Extract HTML comments
  const commentRegex = /<!--([\s\S]*?)-->/g;
  let commentMatch: RegExpExecArray | null;

  while ((commentMatch = commentRegex.exec(html)) !== null) {
    const commentContent = commentMatch[1];

    // Skip copyright / license / attribution comments — they are never sensitive
    if (BENIGN_COMMENT_PATTERNS.some((p) => p.test(commentContent))) continue;

    for (const pattern of SENSITIVE_COMMENT_PATTERNS) {
      const sensitiveRegex = new RegExp(pattern.source, 'i');
      if (sensitiveRegex.test(commentContent)) {
        // Truncate long comments for display
        const truncated = commentContent.trim().slice(0, 200);
        if (!matches.some((m) => m.includes(truncated.slice(0, 50)))) {
          matches.push(truncated);
        }
      }
    }
  }

  if (matches.length > 0) {
    const evidence = matches.slice(0, 5).join(' | ');
    const details = matches.length > 5
      ? `Found ${matches.length} sensitive comments: ${evidence}`
      : `Found ${matches.length} sensitive comment(s)`;

    findings.push(
      entryToFinding(INFO_SENSITIVE_COMMENTS, { evidence, details }, locale),
    );
  }

  return findings;
}

function detectExposedApiKeys(html: string, locale: Locale): ScanFinding[] {
  // This is handled separately from js-analyzer which focuses on script content.
  // Here we look at meta tags and hidden inputs specifically.
  const findings: ScanFinding[] = [];
  const leaks: string[] = [];

  // Check meta tags
  for (const pattern of META_API_KEY_PATTERNS) {
    const regex = new RegExp(pattern.source, 'gi');
    let match: RegExpExecArray | null;
    while ((match = regex.exec(html)) !== null) {
      const keyName = match[0].match(/name\s*=\s*["']([^"']+)["']/i)?.[1] || 'unknown';
      const keyValue = match[1] || match[0].match(/content\s*=\s*["']([^"']+)["']/i)?.[1] || '';
      // Mask the key value for safety
      const masked = keyValue.length > 8
        ? `${keyValue.slice(0, 4)}...${keyValue.slice(-4)}`
        : '(key found)';
      leaks.push(`${keyName}: ${masked}`);
    }
  }

  // Check hidden inputs
  for (const pattern of HIDDEN_INPUT_PATTERNS) {
    const regex = new RegExp(pattern.source, 'gi');
    let match: RegExpExecArray | null;
    while ((match = regex.exec(html)) !== null) {
      const inputName = match[0].match(/name\s*=\s*["']([^"']+)["']/i)?.[1] || 'unknown';
      const inputValue = match[1] || '';
      const masked = inputValue.length > 8
        ? `${inputValue.slice(0, 4)}...${inputValue.slice(-4)}`
        : '(value found)';
      leaks.push(`Hidden input "${inputName}": ${masked}`);
    }
  }

  if (leaks.length > 0) {
    // Create a finding using SENSITIVE_COMMENTS entry since we don't have a dedicated one
    // and the severity matches. Note: the evidence clearly differentiates this from
    // actual sensitive comment findings (meta/hidden input API keys vs HTML comments).
    const evidence = leaks.slice(0, 5).join(', ');
    findings.push(
      entryToFinding(INFO_SENSITIVE_COMMENTS, {
        evidence,
        details: `Exposed API keys/tokens in meta tags or hidden inputs: ${evidence}`,
      }, locale),
    );
  }

  return findings;
}

function detectInternalIps(html: string, locale: Locale): ScanFinding[] {
  const findings: ScanFinding[] = [];
  const found: string[] = [];

  // Remove script, style, SVG, and noscript content
  const cleanHtml = html.replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<svg[\s\S]*?<\/svg>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ');

  // Check internal IPs
  for (const pattern of INTERNAL_IP_PATTERNS) {
    const regex = new RegExp(pattern.source, 'g');
    let match: RegExpExecArray | null;
    while ((match = regex.exec(cleanHtml)) !== null) {
      if (!found.includes(match[0])) {
        found.push(match[0]);
      }
    }
  }

  // Check internal hostnames
  for (const pattern of INTERNAL_HOSTNAME_PATTERNS) {
    const regex = new RegExp(pattern.source, 'gi');
    let match: RegExpExecArray | null;
    while ((match = regex.exec(cleanHtml)) !== null) {
      const trimmed = match[0].trim();
      if (!found.includes(trimmed)) {
        found.push(trimmed);
      }
    }
  }

  if (found.length > 0) {
    const evidence = found.slice(0, 10).join(', ');
    const details = found.length > 10
      ? `Found ${found.length} internal references: ${evidence}`
      : `Found internal reference(s): ${evidence}`;

    findings.push(
      entryToFinding(INFO_INTERNAL_IP, { evidence, details }, locale),
    );
  }

  return findings;
}

function detectOpenRedirect(html: string, pageUrl: string, locale: Locale): ScanFinding[] {
  const findings: ScanFinding[] = [];

  let match: RegExpExecArray | null;
  const regex = new RegExp(META_REFRESH_PATTERN.source, 'gi');
  while ((match = regex.exec(html)) !== null) {
    const delay = match[1];
    const targetUrl = match[2].trim();

    // Check if redirect goes to external domain
    try {
      const pageHost = new URL(pageUrl).hostname;
      const targetHost = new URL(targetUrl, pageUrl).hostname;

      if (pageHost !== targetHost) {
        findings.push(
          entryToFinding(INFO_OPEN_REDIRECT, {
            evidence: `<meta http-equiv="refresh" content="${delay}; url=${targetUrl}">`,
            details: `Meta refresh redirects to external domain: ${targetHost} (delay: ${delay}s)`,
          }, locale),
        );
      }
    } catch {
      // Invalid URL in meta refresh, still flag it if it looks external
      if (/^https?:\/\//i.test(targetUrl)) {
        findings.push(
          entryToFinding(INFO_OPEN_REDIRECT, {
            evidence: `<meta http-equiv="refresh" content="${delay}; url=${targetUrl}">`,
            details: `Meta refresh redirects to external URL: ${targetUrl}`,
          }, locale),
        );
      }
    }
  }

  return findings;
}

// Stack trace / debug page signatures
const STACK_TRACE_PATTERNS: Array<{ regex: RegExp; label: string }> = [
  // Django debug page
  { regex: /django\.(?:core|db|http|template)\.exceptions/i, label: 'Django exception traceback' },
  { regex: /Traceback \(most recent call last\):/i, label: 'Python traceback' },
  // PHP errors
  { regex: /(?:Fatal error|Parse error|Warning|Notice):\s+\w+\s+in\s+\/[^\s<]+\s+on line \d+/i, label: 'PHP error' },
  { regex: /<b>(?:Fatal error|Parse error|Warning)<\/b>:/i, label: 'PHP error (HTML)' },
  { regex: /Stack trace:\s*\n(?:\s*#\d+\s+.+\n)+/i, label: 'PHP stack trace' },
  // Rails
  { regex: /ActionController::RoutingError|ActiveRecord::RecordNotFound/i, label: 'Rails exception' },
  { regex: /app\/controllers\/[^\s]+\.rb:\d+:in/i, label: 'Rails stack trace' },
  // Laravel
  { regex: /Illuminate\\[A-Za-z\\]+Exception/i, label: 'Laravel exception' },
  { regex: /\[previous exception\].*Illuminate/i, label: 'Laravel exception chain' },
  // Node.js / Express
  { regex: /at\s+\w+\s+\([^)]+\.js:\d+:\d+\)\n\s+at\s+/i, label: 'Node.js stack trace' },
  { regex: /Error: ENOENT|EACCES|ETIMEDOUT.*node_modules/i, label: 'Node.js runtime error' },
  // Java Spring
  { regex: /java\.(?:lang|io|net|util)\.\w+Exception/i, label: 'Java exception' },
  { regex: /org\.springframework\.\w+Exception/i, label: 'Spring exception' },
  { regex: /at\s+[\w.$]+\([\w.]+\.java:\d+\)/i, label: 'Java stack trace' },
  // ASP.NET
  { regex: /System\.(?:Web|Data|IO|Exception)\.\w+Exception/i, label: 'ASP.NET exception' },
  // Generic whoops / debug pages
  { regex: /Whoops[!\s]+There was an error/i, label: 'Whoops error page' },
  { regex: /xdebug-error xe-notice|xdebug-info/i, label: 'Xdebug output' },
  // Server error leaking paths
  { regex: /in \/(?:var|home|srv|opt|usr)\/[^\s<]+\.(?:php|py|rb|js|ts)(?:\s+on line)?\s+\d+/i, label: 'Server path disclosure in error' },
];

function detectStackTraces(html: string, locale: Locale): ScanFinding[] {
  for (const { regex, label } of STACK_TRACE_PATTERNS) {
    if (regex.test(html)) {
      const match = html.match(regex);
      const snippet = match ? match[0].slice(0, 120).replace(/\s+/g, ' ') : label;
      return [entryToFinding(STACK_TRACE_EXPOSED, {
        evidence: locale === 'uk' ? `Виявлено: ${label}`
          : locale === 'ru' ? `Обнаружено: ${label}`
          : `Detected: ${label}`,
        details: locale === 'uk'
          ? `Сторінка містить stack trace або повідомлення про помилку: "${snippet}". Це розкриває внутрішню структуру додатку.`
          : locale === 'ru'
          ? `Страница содержит stack trace или сообщение об ошибке: "${snippet}". Это раскрывает внутреннюю структуру приложения.`
          : `Page contains a stack trace or error message: "${snippet}". This exposes internal application structure.`,
      }, locale)];
    }
  }
  return [];
}

// ---- Main detection function ----

export function detectInfoLeakage(
  page: { body: string; url: string },
  locale: Locale = 'en',
): InfoLeakageResult {
  const findings: ScanFinding[] = [];

  // Run all detection phases
  findings.push(...detectEmailLeakage(page.body, locale));
  findings.push(...detectPhoneLeakage(page.body, locale));
  findings.push(...detectSensitiveComments(page.body, locale));
  findings.push(...detectExposedApiKeys(page.body, locale));
  findings.push(...detectInternalIps(page.body, locale));
  findings.push(...detectOpenRedirect(page.body, page.url, locale));
  findings.push(...detectStackTraces(page.body, locale));

  return { findings };
}
